### ISSUE TITLE
Misplaced icon

### ISSUE THREAD

**Issue by kernelb00t** [Droidiar/simpleoutline-spicetify#2]
On 1920*1080 display, with Beautiful Lyrics:
![image](https://github.com/Droidiar/simpleoutline-spicetify/assets/68474172/01fa50e3-19e3-419d-b7be-3859d79679f6)

> The "Add to Library" button overlaps the author's name.

**Comment by Droidiar** [comment]
I don't see this on my end? I don't even have an add to library button.

**Comment by kernelb00t** [comment]
I'll close since I don't use your theme anymore, but I was on Arch Linux latest with the latest theme, a Spotify version a bit late behind Windows platform (can't remember). If anyone has this issue, they can open a new one.

The fact that you don't have this button is strange, I see it everywhere. Check on other platforms/if you are up to date
