### ISSUE TITLE
Playbar "Play" button not centered

### ISSUE THREAD

**Issue by kernelb00t** [Droidiar/simpleoutline-spicetify#3]
![image](https://github.com/Droidiar/simpleoutline-spicetify/assets/68474172/eee02162-94e1-4e6c-8120-a3d5ccfc09e0)

**Comment by Droidiar** [comment]
Should hopefully be mostly centered now? It at least looks better

**Comment by Droidiar** [comment]
![image](https://github.com/Droidiar/simpleoutline-spicetify/assets/94680770/425cb9ab-d4e9-49fb-8f95-ec34503c3731)

**Comment by kernelb00t** [comment]
Seems better on your screenshot!
